runtime: python38 

instance_class: F2

handlers:
- url: /static
  static_dir: stickybeak/static

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

env_variables:
  CLOUD_SQL_USERNAME: root
  CLOUD_SQL_PASSWORD: password
  CLOUD_SQL_DATABASE_NAME: newsletter
  CLOUD_SQL_CONNECTION_NAME: foundations-project-310611:europe-west3:fprojectdb