runtime: python38 

instance_class: F2

handlers:
- url: /static
  static_dir: stickybeak/static

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

env_variables:

# ================== Database settings ==================

# mysql_host: 'localhost'
# mysql_user: 'root'
# mysql_password: ''
# mysql_db: 'foundations'