runtime: python38 

instance_class: F2

handlers:
- url: /static
  static_dir: stickybeak/static

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

env_variables:
  CLOUD_SQL_USERNAME: USERNAME
  CLOUD_SQL_PASSWORD: 311MpP0wINeHxGth
  CLOUD_SQL_DATABASE_NAME: foundationsdb
  CLOUD_SQL_CONNECTION_NAME: foundations-project-310611:us-central1:foundationsdb
